"""initial_schema

Revision ID: 0408beae0390
Revises:
Create Date: 2026-04-08 18:30:16.094053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0408beae0390'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_sub', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('preferred_first_name', sa.String(), nullable=True),
    sa.Column('preferred_last_name', sa.String(), nullable=True),
    sa.Column('notion_access_token', sa.String(), nullable=True),
    sa.Column('notion_bot_id', sa.String(), nullable=True),
    sa.Column('notion_workspace_id', sa.String(), nullable=True),
    sa.Column('notion_workspace_name', sa.String(), nullable=True),
    sa.Column('notion_parent_page_id', sa.String(), nullable=True),
    sa.Column('pronouns', sa.String(), nullable=True),
    sa.Column('username_slug', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('profile_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_username_slug'), 'users', ['username_slug'], unique=True)
    op.create_table('experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('extracted_profile', sa.JSON(), nullable=True),
    sa.Column('raw_resume_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('github_username', sa.String(), nullable=True),
    sa.Column('github_repos', sa.JSON(), nullable=True),
    sa.Column('user_input_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_process_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_url', sa.String(), nullable=False),
    sa.Column('extracted_job', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_trigger_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('chunk_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_rationale', sa.Text(), nullable=True),
    sa.Column('advocacy_blurb', sa.Text(), nullable=True),
    sa.Column('experience_source', sa.String(length=50), nullable=True),
    sa.Column('should_render', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tailorings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('generated_output', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('generation_status', sa.String(), server_default='ready', nullable=False),
    sa.Column('generation_stage', sa.String(), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_regenerated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrichment_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('letter_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('posting_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('public_slug', sa.String(), nullable=True),
    sa.Column('notion_container_page_id', sa.String(), nullable=True),
    sa.Column('notion_page_id', sa.String(), nullable=True),
    sa.Column('notion_page_url', sa.String(), nullable=True),
    sa.Column('notion_posting_page_id', sa.String(), nullable=True),
    sa.Column('notion_posting_page_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'public_slug', name='uq_tailorings_user_public_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tailorings')
    op.drop_table('job_chunks')
    op.drop_table('llm_trigger_log')
    op.drop_table('jobs')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_users_username_slug'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
