"""add_user_input_text_to_experiences

Revision ID: 2696096fffe0
Revises: 967e51ce9415
Create Date: 2026-02-28 11:25:02.140066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2696096fffe0'
down_revision: Union[str, Sequence[str], None] = '967e51ce9415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('user_input_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'user_input_text')
    # ### end Alembic commands ###
