"""add raw_resume_text to experiences

Revision ID: 43311df5f40b
Revises: b5d8e2f1a9c3
Create Date: 2026-03-11 22:00:40.534649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43311df5f40b'
down_revision: Union[str, Sequence[str], None] = 'b5d8e2f1a9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('raw_resume_text', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_job_chunks_job_id'), table_name='job_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_chunks_job_id'), 'job_chunks', ['job_id'], unique=False)
    op.drop_column('experiences', 'raw_resume_text')
    # ### end Alembic commands ###
