"""tailoring_generation_telemetry

Revision ID: bf025e128dff
Revises: 0408beae0390
Create Date: 2026-04-10 18:59:50.194230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf025e128dff'
down_revision: Union[str, Sequence[str], None] = '0408beae0390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailorings', sa.Column('generation_duration_ms', sa.Integer(), nullable=True))
    op.add_column('tailorings', sa.Column('chunk_batch_count', sa.Integer(), nullable=True))
    op.add_column('tailorings', sa.Column('chunk_error_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tailorings', 'chunk_error_count')
    op.drop_column('tailorings', 'chunk_batch_count')
    op.drop_column('tailorings', 'generation_duration_ms')
    # ### end Alembic commands ###
