name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: tailord

jobs:

  deploy:

    runs-on: ubuntu-latest

    environment: 
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate date and build number
      id: generate_tag
      run: |
          # Get current date in YYYYMMDD format
          BUILD_DATE=$(date +'%Y%m%d')
          # Get the unique run number for the current workflow
          BUILD_NUM=${{ github.run_number }}
          # Combine them into a tag name, e.g., 'v20260104.1'
          TAG_NAME="$BUILD_DATE.$BUILD_NUM"
          # Set the tag name as an output for subsequent steps
          echo "Generated tag name: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      env:
        IMAGE_TAG: ${{ steps.generate_tag.outputs.TAG_NAME }}
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          $(aws sts get-caller-identity --query Account --output text).dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
        docker push \
          $(aws sts get-caller-identity --query Account --output text).dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
        
